-- Fresh-install baseline of the existing private application schema.
-- Run only when hub_user does not exist, using the dedicated role search_path.
-- Existing installations keep all current tables and data; do not replay this file.

CREATE TABLE hub_achievement (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    slug character varying(50) NOT NULL,
    title character varying(300) NOT NULL,
    description text NOT NULL,
    icon character varying(30) NOT NULL
);

CREATE TABLE hub_activity (
    user_id uuid NOT NULL,
    visit_count integer NOT NULL,
    total_seconds integer NOT NULL,
    last_seen_at timestamp with time zone NOT NULL,
    CONSTRAINT hub_activity_total_seconds_check CHECK ((total_seconds >= 0)),
    CONSTRAINT hub_activity_visit_count_check CHECK ((visit_count >= 0))
);

CREATE TABLE hub_award (
    id uuid NOT NULL,
    detail text NOT NULL,
    awarded_at timestamp with time zone NOT NULL,
    achievement_id uuid NOT NULL,
    user_id uuid NOT NULL
);

CREATE TABLE hub_bounty (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    slug character varying(50) NOT NULL,
    title character varying(300) NOT NULL,
    description text NOT NULL,
    icon character varying(30) NOT NULL,
    claimed_at timestamp with time zone,
    claimed_by_id uuid
);

CREATE TABLE hub_dailyscore (
    id bigint NOT NULL,
    day date NOT NULL,
    imported boolean NOT NULL,
    score double precision,
    game_id integer NOT NULL,
    user_id uuid,
    metric character varying(10) NOT NULL,
    CONSTRAINT valid_score_metric CHECK (((metric)::text = ANY ((ARRAY['enjoyment'::character varying, 'difficulty'::character varying])::text[])))
);

ALTER TABLE hub_dailyscore ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME hub_dailyscore_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE hub_expansion (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    name character varying(500) NOT NULL,
    bgg_expansion_id integer,
    thumbnail_url character varying(1000) NOT NULL,
    game_id integer NOT NULL,
    CONSTRAINT hub_expansion_bgg_expansion_id_check CHECK ((bgg_expansion_id >= 0))
);

CREATE TABLE hub_expansionplacement (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    tier character varying(1) NOT NULL,
    "position" integer NOT NULL,
    score double precision,
    updated_at timestamp with time zone NOT NULL,
    expansion_id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT hub_expansionplacement_position_check CHECK (("position" >= 0)),
    CONSTRAINT valid_expansion_tier CHECK (((tier)::text = ANY ((ARRAY['S'::character varying, 'A'::character varying, 'B'::character varying, 'C'::character varying, 'D'::character varying, 'F'::character varying])::text[])))
);

CREATE TABLE hub_feedback (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    title character varying(300) NOT NULL,
    description text NOT NULL,
    category character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    admin_note text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id uuid NOT NULL
);

CREATE TABLE hub_game (
    bgg_id integer NOT NULL,
    name character varying(500) NOT NULL,
    description text NOT NULL,
    image_url character varying(1000) NOT NULL,
    thumbnail_url character varying(1000) NOT NULL,
    category character varying(5) NOT NULL,
    year_published integer,
    min_players integer,
    max_players integer,
    playing_time integer,
    min_play_time integer,
    max_play_time integer,
    min_age integer,
    bgg_rating double precision,
    categories jsonb NOT NULL,
    mechanics jsonb NOT NULL,
    designers jsonb NOT NULL,
    artists jsonb NOT NULL,
    publishers jsonb NOT NULL,
    alternate_names jsonb NOT NULL,
    expansions jsonb NOT NULL,
    suggested_players jsonb NOT NULL,
    suggested_age integer,
    language_dependence text NOT NULL,
    bgg_users_rated integer,
    bgg_std_dev double precision,
    bgg_owned integer,
    bgg_wanting integer,
    bgg_wishing integer,
    fetched_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT hub_game_bgg_id_check CHECK ((bgg_id >= 0)),
    CONSTRAINT hub_game_bgg_owned_check CHECK ((bgg_owned >= 0)),
    CONSTRAINT hub_game_bgg_users_rated_check CHECK ((bgg_users_rated >= 0)),
    CONSTRAINT hub_game_bgg_wanting_check CHECK ((bgg_wanting >= 0)),
    CONSTRAINT hub_game_bgg_wishing_check CHECK ((bgg_wishing >= 0)),
    CONSTRAINT hub_game_max_play_time_check CHECK ((max_play_time >= 0)),
    CONSTRAINT hub_game_max_players_check CHECK ((max_players >= 0)),
    CONSTRAINT hub_game_min_age_check CHECK ((min_age >= 0)),
    CONSTRAINT hub_game_min_play_time_check CHECK ((min_play_time >= 0)),
    CONSTRAINT hub_game_min_players_check CHECK ((min_players >= 0)),
    CONSTRAINT hub_game_playing_time_check CHECK ((playing_time >= 0)),
    CONSTRAINT hub_game_suggested_age_check CHECK ((suggested_age >= 0))
);

CREATE TABLE hub_rulebook (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    module_name character varying(300) NOT NULL,
    module_type character varying(10) NOT NULL,
    content_md text NOT NULL,
    token_estimate integer,
    source text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id uuid,
    game_id integer NOT NULL,
    CONSTRAINT hub_rulebook_token_estimate_check CHECK ((token_estimate >= 0))
);

CREATE TABLE hub_rulesanswer (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    modules_hash character varying(64) NOT NULL,
    question_norm text NOT NULL,
    answer_md text NOT NULL,
    citations jsonb NOT NULL,
    game_id integer NOT NULL
);

CREATE TABLE hub_rulesrun (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    question text NOT NULL,
    answer_md text NOT NULL,
    citations jsonb NOT NULL,
    tool_calls jsonb NOT NULL,
    cache_hit boolean NOT NULL,
    game_id integer,
    user_id uuid
);

CREATE TABLE hub_user (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    display_name character varying(150) NOT NULL,
    avatar_url character varying(1000) NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    partner_id uuid
);

CREATE TABLE hub_usergame (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    owned boolean NOT NULL,
    wishlist boolean NOT NULL,
    wishlist_priority smallint,
    wishlist_note text NOT NULL,
    collection_added_at timestamp with time zone,
    rating double precision,
    comment text NOT NULL,
    rating_created_at timestamp with time zone,
    rating_updated_at timestamp with time zone,
    tier character varying(1) NOT NULL,
    "position" integer NOT NULL,
    score double precision,
    tier_created_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL,
    legacy_ids jsonb NOT NULL,
    game_id integer NOT NULL,
    user_id uuid NOT NULL,
    difficulty_position integer NOT NULL,
    difficulty_tier smallint,
    difficulty_updated_at timestamp with time zone,
    CONSTRAINT hub_usergame_difficulty_position_check CHECK ((difficulty_position >= 0)),
    CONSTRAINT hub_usergame_difficulty_tier_check CHECK ((difficulty_tier >= 0)),
    CONSTRAINT hub_usergame_position_check CHECK (("position" >= 0)),
    CONSTRAINT hub_usergame_wishlist_priority_check CHECK ((wishlist_priority >= 0)),
    CONSTRAINT unranked_difficulty_state CHECK (((difficulty_tier IS NOT NULL) OR (difficulty_position = 0))),
    CONSTRAINT unranked_game_state CHECK (((NOT ((tier)::text = ''::text)) OR (("position" = 0) AND (score IS NULL)))),
    CONSTRAINT valid_difficulty_tier CHECK (((difficulty_tier IS NULL) OR ((difficulty_tier >= 1) AND (difficulty_tier <= 6)))),
    CONSTRAINT valid_game_rating CHECK (((rating IS NULL) OR ((rating >= (1.0)::double precision) AND (rating <= (10.0)::double precision)))),
    CONSTRAINT valid_game_score CHECK (((score IS NULL) OR ((score >= (1.0)::double precision) AND (score <= (10.0)::double precision)))),
    CONSTRAINT valid_game_tier CHECK (((tier)::text = ANY ((ARRAY[''::character varying, 'S'::character varying, 'A'::character varying, 'B'::character varying, 'C'::character varying, 'D'::character varying, 'F'::character varying])::text[]))),
    CONSTRAINT valid_wishlist_priority CHECK (((wishlist_priority IS NULL) OR ((wishlist_priority >= 1) AND (wishlist_priority <= 3))))
);

ALTER TABLE ONLY hub_achievement
    ADD CONSTRAINT hub_achievement_pkey PRIMARY KEY (id);

ALTER TABLE ONLY hub_achievement
    ADD CONSTRAINT hub_achievement_slug_key UNIQUE (slug);

ALTER TABLE ONLY hub_activity
    ADD CONSTRAINT hub_activity_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY hub_award
    ADD CONSTRAINT hub_award_pkey PRIMARY KEY (id);

ALTER TABLE ONLY hub_bounty
    ADD CONSTRAINT hub_bounty_pkey PRIMARY KEY (id);

ALTER TABLE ONLY hub_bounty
    ADD CONSTRAINT hub_bounty_slug_key UNIQUE (slug);

ALTER TABLE ONLY hub_dailyscore
    ADD CONSTRAINT hub_dailyscore_pkey PRIMARY KEY (id);

ALTER TABLE ONLY hub_expansion
    ADD CONSTRAINT hub_expansion_pkey PRIMARY KEY (id);

ALTER TABLE ONLY hub_expansionplacement
    ADD CONSTRAINT hub_expansionplacement_pkey PRIMARY KEY (id);

ALTER TABLE ONLY hub_feedback
    ADD CONSTRAINT hub_feedback_pkey PRIMARY KEY (id);

ALTER TABLE ONLY hub_game
    ADD CONSTRAINT hub_game_pkey PRIMARY KEY (bgg_id);

ALTER TABLE ONLY hub_rulebook
    ADD CONSTRAINT hub_rulebook_pkey PRIMARY KEY (id);

ALTER TABLE ONLY hub_rulesanswer
    ADD CONSTRAINT hub_rulesanswer_pkey PRIMARY KEY (id);

ALTER TABLE ONLY hub_rulesrun
    ADD CONSTRAINT hub_rulesrun_pkey PRIMARY KEY (id);

ALTER TABLE ONLY hub_user
    ADD CONSTRAINT hub_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY hub_user
    ADD CONSTRAINT hub_user_username_key UNIQUE (username);

ALTER TABLE ONLY hub_usergame
    ADD CONSTRAINT hub_usergame_pkey PRIMARY KEY (id);

ALTER TABLE ONLY hub_award
    ADD CONSTRAINT unique_award UNIQUE (user_id, achievement_id);

ALTER TABLE ONLY hub_expansion
    ADD CONSTRAINT unique_expansion UNIQUE (game_id, name);

ALTER TABLE ONLY hub_expansionplacement
    ADD CONSTRAINT unique_expansion_placement UNIQUE (user_id, expansion_id);

ALTER TABLE ONLY hub_rulebook
    ADD CONSTRAINT unique_rulebook UNIQUE (game_id, module_name);

ALTER TABLE ONLY hub_rulesanswer
    ADD CONSTRAINT unique_rules_answer UNIQUE (game_id, modules_hash, question_norm);

ALTER TABLE ONLY hub_usergame
    ADD CONSTRAINT unique_user_game UNIQUE (user_id, game_id);

CREATE INDEX hub_achievement_slug_ee49e7e0_like ON hub_achievement USING btree (slug varchar_pattern_ops);

CREATE INDEX hub_award_achievement_id_8048c6ba ON hub_award USING btree (achievement_id);

CREATE INDEX hub_award_user_id_50c5ffb9 ON hub_award USING btree (user_id);

CREATE INDEX hub_bounty_claimed_by_id_506ffe69 ON hub_bounty USING btree (claimed_by_id);

CREATE INDEX hub_bounty_slug_3a6f402b_like ON hub_bounty USING btree (slug varchar_pattern_ops);

CREATE INDEX hub_dailysc_metric_748e1b_idx ON hub_dailyscore USING btree (metric, game_id, day);

CREATE INDEX hub_expansionplacement_expansion_id_3eefe78a ON hub_expansionplacement USING btree (expansion_id);

CREATE INDEX hub_expansionplacement_user_id_58b24732 ON hub_expansionplacement USING btree (user_id);

CREATE INDEX hub_feedback_user_id_18643956 ON hub_feedback USING btree (user_id);

CREATE INDEX hub_game_category_920df69f ON hub_game USING btree (category);

CREATE INDEX hub_game_category_920df69f_like ON hub_game USING btree (category varchar_pattern_ops);

CREATE INDEX hub_rulebook_created_by_id_2f81f2aa ON hub_rulebook USING btree (created_by_id);

CREATE INDEX hub_rulesrun_game_id_52af1e08 ON hub_rulesrun USING btree (game_id);

CREATE INDEX hub_rulesrun_user_id_c2ec4d01 ON hub_rulesrun USING btree (user_id);

CREATE INDEX hub_user_partner_id_150afbf2 ON hub_user USING btree (partner_id);

CREATE INDEX hub_user_username_dca480f5_like ON hub_user USING btree (username varchar_pattern_ops);

CREATE INDEX hub_usergame_game_id_3d956295 ON hub_usergame USING btree (game_id);

CREATE UNIQUE INDEX unique_daily_community_score ON hub_dailyscore USING btree (metric, game_id, day) WHERE (user_id IS NULL);

CREATE UNIQUE INDEX unique_daily_player_score ON hub_dailyscore USING btree (metric, user_id, game_id, day) WHERE (user_id IS NOT NULL);

ALTER TABLE ONLY hub_activity
    ADD CONSTRAINT hub_activity_user_id_a100b9b1_fk_hub_user_id FOREIGN KEY (user_id) REFERENCES hub_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_award
    ADD CONSTRAINT hub_award_achievement_id_8048c6ba_fk_hub_achievement_id FOREIGN KEY (achievement_id) REFERENCES hub_achievement(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_award
    ADD CONSTRAINT hub_award_user_id_50c5ffb9_fk_hub_user_id FOREIGN KEY (user_id) REFERENCES hub_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_bounty
    ADD CONSTRAINT hub_bounty_claimed_by_id_506ffe69_fk_hub_user_id FOREIGN KEY (claimed_by_id) REFERENCES hub_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_dailyscore
    ADD CONSTRAINT hub_dailyscore_game_id_af90c58c_fk_hub_game_bgg_id FOREIGN KEY (game_id) REFERENCES hub_game(bgg_id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_dailyscore
    ADD CONSTRAINT hub_dailyscore_user_id_443c4cac_fk_hub_user_id FOREIGN KEY (user_id) REFERENCES hub_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_expansion
    ADD CONSTRAINT hub_expansion_game_id_ab15ab61_fk_hub_game_bgg_id FOREIGN KEY (game_id) REFERENCES hub_game(bgg_id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_expansionplacement
    ADD CONSTRAINT hub_expansionplaceme_expansion_id_3eefe78a_fk_hub_expan FOREIGN KEY (expansion_id) REFERENCES hub_expansion(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_expansionplacement
    ADD CONSTRAINT hub_expansionplacement_user_id_58b24732_fk_hub_user_id FOREIGN KEY (user_id) REFERENCES hub_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_feedback
    ADD CONSTRAINT hub_feedback_user_id_18643956_fk_hub_user_id FOREIGN KEY (user_id) REFERENCES hub_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_rulebook
    ADD CONSTRAINT hub_rulebook_created_by_id_2f81f2aa_fk_hub_user_id FOREIGN KEY (created_by_id) REFERENCES hub_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_rulebook
    ADD CONSTRAINT hub_rulebook_game_id_1721eaea_fk_hub_game_bgg_id FOREIGN KEY (game_id) REFERENCES hub_game(bgg_id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_rulesanswer
    ADD CONSTRAINT hub_rulesanswer_game_id_87b2549d_fk_hub_game_bgg_id FOREIGN KEY (game_id) REFERENCES hub_game(bgg_id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_rulesrun
    ADD CONSTRAINT hub_rulesrun_game_id_52af1e08_fk_hub_game_bgg_id FOREIGN KEY (game_id) REFERENCES hub_game(bgg_id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_rulesrun
    ADD CONSTRAINT hub_rulesrun_user_id_c2ec4d01_fk_hub_user_id FOREIGN KEY (user_id) REFERENCES hub_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_user
    ADD CONSTRAINT hub_user_partner_id_150afbf2_fk_hub_user_id FOREIGN KEY (partner_id) REFERENCES hub_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_usergame
    ADD CONSTRAINT hub_usergame_game_id_3d956295_fk_hub_game_bgg_id FOREIGN KEY (game_id) REFERENCES hub_game(bgg_id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY hub_usergame
    ADD CONSTRAINT hub_usergame_user_id_8e4e39bd_fk_hub_user_id FOREIGN KEY (user_id) REFERENCES hub_user(id) DEFERRABLE INITIALLY DEFERRED;
