# Generated by Django 5.2.17 on 2026-09-28 18:10

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(max_length=150)),
                ("avatar_url", models.URLField(blank=True, max_length=1000)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="🏆", max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("bgg_id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, max_length=1000)),
                ("thumbnail_url", models.URLField(blank=True, max_length=1000)),
                (
                    "category",
                    models.CharField(
                        choices=[("board", "Board games"), ("party", "Party games")],
                        db_index=True,
                        default="board",
                        max_length=5,
                    ),
                ),
                ("year_published", models.IntegerField(blank=True, null=True)),
                ("min_players", models.PositiveIntegerField(blank=True, null=True)),
                ("max_players", models.PositiveIntegerField(blank=True, null=True)),
                ("playing_time", models.PositiveIntegerField(blank=True, null=True)),
                ("min_play_time", models.PositiveIntegerField(blank=True, null=True)),
                ("max_play_time", models.PositiveIntegerField(blank=True, null=True)),
                ("min_age", models.PositiveIntegerField(blank=True, null=True)),
                ("bgg_rating", models.FloatField(blank=True, null=True)),
                ("bgg_weight", models.FloatField(blank=True, null=True)),
                ("categories", models.JSONField(blank=True, default=list)),
                ("mechanics", models.JSONField(blank=True, default=list)),
                ("designers", models.JSONField(blank=True, default=list)),
                ("artists", models.JSONField(blank=True, default=list)),
                ("publishers", models.JSONField(blank=True, default=list)),
                ("alternate_names", models.JSONField(blank=True, default=list)),
                ("expansions", models.JSONField(blank=True, default=list)),
                ("suggested_players", models.JSONField(blank=True, default=list)),
                ("suggested_age", models.PositiveIntegerField(blank=True, null=True)),
                ("language_dependence", models.TextField(blank=True)),
                ("bgg_users_rated", models.PositiveIntegerField(blank=True, null=True)),
                ("bgg_std_dev", models.FloatField(blank=True, null=True)),
                ("bgg_owned", models.PositiveIntegerField(blank=True, null=True)),
                ("bgg_wanting", models.PositiveIntegerField(blank=True, null=True)),
                ("bgg_wishing", models.PositiveIntegerField(blank=True, null=True)),
                ("bgg_num_weights", models.PositiveIntegerField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["name", "bgg_id"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("visit_count", models.PositiveIntegerField(default=0)),
                ("total_seconds", models.PositiveIntegerField(default=0)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Bounty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="🏆", max_length=30)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("feature", "Feature"),
                            ("bug", "Bug"),
                            ("improvement", "Improvement"),
                        ],
                        default="feature",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("planned", "Planned"),
                            ("in-progress", "In-Progress"),
                            ("done", "Done"),
                            ("declined", "Declined"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Expansion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=500)),
                ("bgg_expansion_id", models.PositiveIntegerField(blank=True, null=True)),
                ("thumbnail_url", models.URLField(blank=True, max_length=1000)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankable_expansions",
                        to="hub.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("owned", models.BooleanField(default=False)),
                ("wishlist", models.BooleanField(default=False)),
                (
                    "wishlist_priority",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                ("wishlist_note", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="hub.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("S", "S"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("F", "F"),
                        ],
                        max_length=1,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("score", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="hub.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "rating",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="hub.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rulebook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("module_name", models.CharField(max_length=300)),
                (
                    "module_type",
                    models.CharField(
                        choices=[("base", "Base"), ("expansion", "Expansion")],
                        default="base",
                        max_length=10,
                    ),
                ),
                ("content_md", models.TextField()),
                ("token_estimate", models.PositiveIntegerField(blank=True, null=True)),
                ("source", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rulebooks",
                        to="hub.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RulesAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("modules_hash", models.CharField(max_length=64)),
                ("question_norm", models.TextField()),
                ("answer_md", models.TextField()),
                ("citations", models.JSONField(blank=True, default=list)),
                (
                    "game",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub.game"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RulesRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("question", models.TextField()),
                ("answer_md", models.TextField(blank=True)),
                ("citations", models.JSONField(blank=True, default=list)),
                ("tool_calls", models.JSONField(blank=True, default=list)),
                ("cache_hit", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hub.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("snapshot_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="hub.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("awarded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="hub.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("user", "achievement"), name="unique_award")
                ],
            },
        ),
        migrations.CreateModel(
            name="ExpansionPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("S", "S"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("F", "F"),
                        ],
                        max_length=1,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("score", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "expansion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="hub.expansion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "expansion"), name="unique_expansion_placement"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("tier__in", ["S", "A", "B", "C", "D", "F"])),
                        name="valid_expansion_tier",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="expansion",
            constraint=models.UniqueConstraint(fields=("game", "name"), name="unique_expansion"),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(fields=("user", "game"), name="unique_collection"),
        ),
        migrations.AddConstraint(
            model_name="placement",
            constraint=models.UniqueConstraint(fields=("user", "game"), name="unique_placement"),
        ),
        migrations.AddConstraint(
            model_name="placement",
            constraint=models.CheckConstraint(
                condition=models.Q(("tier__in", ["S", "A", "B", "C", "D", "F"])),
                name="valid_game_tier",
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(fields=("user", "game"), name="unique_rating"),
        ),
        migrations.AddConstraint(
            model_name="rulebook",
            constraint=models.UniqueConstraint(
                fields=("game", "module_name"), name="unique_rulebook"
            ),
        ),
        migrations.AddConstraint(
            model_name="rulesanswer",
            constraint=models.UniqueConstraint(
                fields=("game", "modules_hash", "question_norm"), name="unique_rules_answer"
            ),
        ),
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(
                fields=["game", "snapshot_at"], name="hub_snapsho_game_id_e3b730_idx"
            ),
        ),
    ]
