# Generated by Django 5.2.17 on 2026-09-28 19:56

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def consolidate(apps, schema_editor):
    # Frozen migration logic: never import runtime models or scoring functions here.
    import math
    from collections import defaultdict
    from zoneinfo import ZoneInfo

    alias = schema_editor.connection.alias
    UserGame = apps.get_model("hub", "UserGame")
    DailyScore = apps.get_model("hub", "DailyScore")
    merged = {}
    for name, source_name in [
        ("Collection", "user_game_collection"),
        ("Rating", "game_ratings"),
        ("Placement", "tier_placements"),
    ]:
        for old in apps.get_model("hub", name).objects.using(alias).all():
            if name == "Collection" and not (
                old.owned or old.wishlist or old.wishlist_priority or old.wishlist_note.strip()
            ):
                continue
            key = (old.user_id, old.game_id)
            row = merged.setdefault(
                key, UserGame(user_id=old.user_id, game_id=old.game_id, created_at=old.created_at)
            )
            row.created_at = min(row.created_at, old.created_at)
            row.legacy_ids[source_name] = str(old.pk)
            if name == "Collection":
                for field in ["owned", "wishlist", "wishlist_priority", "wishlist_note"]:
                    setattr(row, field, getattr(old, field))
                row.collection_added_at = old.created_at
            elif name == "Rating":
                row.rating, row.comment = old.rating, old.comment
                row.rating_created_at, row.rating_updated_at = old.created_at, old.updated_at
            else:
                row.tier, row.position, row.score = old.tier, old.position, old.score
                row.tier_created_at, row.updated_at = old.created_at, old.updated_at
    UserGame.objects.using(alias).bulk_create(merged.values())

    daily = {}
    zone = ZoneInfo("America/Indiana/Indianapolis")
    for old in apps.get_model("hub", "Snapshot").objects.using(alias).order_by("snapshot_at", "pk"):
        daily[(old.user_id, old.game_id, old.snapshot_at.astimezone(zone).date())] = old.score

    # Resolve legacy position ties and stale scores deterministically, preserving old days.
    now = django.utils.timezone.now()
    groups = defaultdict(list)
    for row in UserGame.objects.using(alias).exclude(tier="").select_related("game"):
        groups[(row.user_id, row.game.category)].append(row)
    for group in groups.values():
        group.sort(key=lambda row: ("SABCDF".index(row.tier), row.position, row.game_id))
        positions = defaultdict(int)
        step = 9 / (len(group) - 1) if len(group) > 1 else 0
        for index, row in enumerate(group):
            row.score = math.floor((10 - index * step) * 10 + 0.5) / 10
            row.position = positions[row.tier]
            positions[row.tier] += 1
            row.updated_at = now
        UserGame.objects.using(alias).bulk_update(group, ["score", "position", "updated_at"])
    day = now.astimezone(zone).date()
    current, averages = {}, defaultdict(list)
    for row in UserGame.objects.using(alias).exclude(tier=""):
        current[(row.user_id, row.game_id)] = row.score
        if row.score is not None:
            averages[row.game_id].append(row.score)
    personal = {(uid, gid) for uid, gid, _ in daily if uid is not None} | current.keys()
    for uid, gid in personal:
        daily[(uid, gid, day)] = current.get((uid, gid))
    for gid in {gid for _, gid, _ in daily} | averages.keys():
        values = averages[gid]
        daily[(None, gid, day)] = sum(values) / len(values) if values else None
    DailyScore.objects.using(alias).bulk_create(
        DailyScore(user_id=uid, game_id=gid, day=date, score=score, imported=date != day)
        for (uid, gid, date), score in daily.items()
    )


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expansion",
            name="game",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rankable_expansions",
                to="hub.game",
            ),
        ),
        migrations.AlterField(
            model_name="rulebook",
            name="game",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rulebooks",
                to="hub.game",
            ),
        ),
        migrations.AlterField(
            model_name="rulesanswer",
            name="game",
            field=models.ForeignKey(
                db_index=False, on_delete=django.db.models.deletion.CASCADE, to="hub.game"
            ),
        ),
        migrations.CreateModel(
            name="DailyScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day", models.DateField(default=django.utils.timezone.localdate)),
                ("imported", models.BooleanField(default=False)),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_scores",
                        to="hub.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["day", "pk"],
            },
        ),
        migrations.CreateModel(
            name="UserGame",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("owned", models.BooleanField(default=False)),
                ("wishlist", models.BooleanField(default=False)),
                (
                    "wishlist_priority",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                ("wishlist_note", models.TextField(blank=True)),
                ("collection_added_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rating",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("rating_created_at", models.DateTimeField(blank=True, null=True)),
                ("rating_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "S"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("F", "F"),
                        ],
                        max_length=1,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("score", models.FloatField(blank=True, null=True)),
                ("tier_created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("legacy_ids", models.JSONField(blank=True, default=dict)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_games",
                        to="hub.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            consolidate
        ),  # Restore the pre-migration backup to undo daily compaction.
        migrations.DeleteModel(
            name="Collection",
        ),
        migrations.DeleteModel(
            name="Placement",
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
        migrations.DeleteModel(
            name="Snapshot",
        ),
        migrations.AddIndex(
            model_name="dailyscore",
            index=models.Index(fields=["game", "day"], name="hub_dailysc_game_id_151696_idx"),
        ),
        migrations.AddConstraint(
            model_name="dailyscore",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "game", "day"),
                name="unique_daily_player_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyscore",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("game", "day"),
                name="unique_daily_community_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="usergame",
            constraint=models.UniqueConstraint(fields=("user", "game"), name="unique_user_game"),
        ),
        migrations.AddConstraint(
            model_name="usergame",
            constraint=models.CheckConstraint(
                condition=models.Q(("tier__in", ["", "S", "A", "B", "C", "D", "F"])),
                name="valid_game_tier",
            ),
        ),
        migrations.AddConstraint(
            model_name="usergame",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rating__isnull", True),
                    models.Q(("rating__gte", 1), ("rating__lte", 10)),
                    _connector="OR",
                ),
                name="valid_game_rating",
            ),
        ),
        migrations.AddConstraint(
            model_name="usergame",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("score__isnull", True),
                    models.Q(("score__gte", 1), ("score__lte", 10)),
                    _connector="OR",
                ),
                name="valid_game_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="usergame",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("tier", ""), _negated=True),
                    models.Q(("position", 0), ("score__isnull", True)),
                    _connector="OR",
                ),
                name="unranked_game_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="usergame",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("wishlist_priority__isnull", True),
                    models.Q(("wishlist_priority__gte", 1), ("wishlist_priority__lte", 3)),
                    _connector="OR",
                ),
                name="valid_wishlist_priority",
            ),
        ),
    ]
