# Generated by Django 5.2.17 on 2026-09-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0002_daily_scores_user_games"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dailyscore",
            name="unique_daily_player_score",
        ),
        migrations.RemoveConstraint(
            model_name="dailyscore",
            name="unique_daily_community_score",
        ),
        migrations.RemoveIndex(
            model_name="dailyscore",
            name="hub_dailysc_game_id_151696_idx",
        ),
        migrations.AddField(
            model_name="dailyscore",
            name="metric",
            field=models.CharField(
                choices=[("enjoyment", "Enjoyment"), ("difficulty", "Difficulty")],
                default="enjoyment",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="usergame",
            name="difficulty_position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usergame",
            name="difficulty_tier",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Cuddly"),
                    (2, "Tame"),
                    (3, "Challenging"),
                    (4, "Demanding"),
                    (5, "Brutal"),
                    (6, "Monstrous"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usergame",
            name="difficulty_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="dailyscore",
            index=models.Index(
                fields=["metric", "game", "day"], name="hub_dailysc_metric_748e1b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyscore",
            constraint=models.CheckConstraint(
                condition=models.Q(("metric__in", ["enjoyment", "difficulty"])),
                name="valid_score_metric",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyscore",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("metric", "user", "game", "day"),
                name="unique_daily_player_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyscore",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("metric", "game", "day"),
                name="unique_daily_community_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="usergame",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("difficulty_tier__isnull", True),
                    models.Q(("difficulty_tier__gte", 1), ("difficulty_tier__lte", 6)),
                    _connector="OR",
                ),
                name="valid_difficulty_tier",
            ),
        ),
        migrations.AddConstraint(
            model_name="usergame",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("difficulty_tier__isnull", False), ("difficulty_position", 0), _connector="OR"
                ),
                name="unranked_difficulty_state",
            ),
        ),
    ]
